name: QA on merge group protected branch PR merge

on:
  merge_group:
  pull_request:

jobs:
  deploy-e2e-flex:
    if: ${{ github.event_name == 'merge_group' }}
    uses: ./.github/workflows/flex-deploy.yml
    secrets: inherit
    with:
      helpline_code: E2E
      environment_code: DEV
      changelog: "Automated release"
      send-slack-message: 'false'

  deploy-e2e-webchat:
    if: ${{ github.event_name == 'merge_group' }}
    uses: ./.github/workflows/webchat-deploy.yml
    secrets: inherit
    with:
      helpline_code: E2E
      environment: development
      send-slack-message: 'false'

  run-e2e-tests:
    needs: [deploy-e2e-flex, deploy-e2e-webchat]
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Flex Plugin
        uses: ./.github/actions/install-flex-plugin

      - name: Run e2e tests
        uses: ./.github/actions/run-e2e-tests
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create Version Tag
        id: create-version-tag
        uses: ./.github/actions/create-tag-based-on-regex
        with:
          search_text: ${{ github.event.merge_group.head_commit.message }}
          regex: 'v[0-9]+\.[0-9]+\.[0-9]+'

      - name: Create Ticket Tag
        if: ${{ steps.create-version-tag.outputs.tag_created == 'false' }}
        uses: ./.github/actions/create-tag-based-on-regex
        with:
          search_text: ${{ github.event.merge_group.head_commit.message }}
          regex: 'CHI-[0-9]+'
